
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - config/**/*.rb
    - bin/*
    - Gemfile

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*.rb
