AllCops:
  Include:
    - Rakefile
    - Guardfile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - node_modules/**/*
    - db/schema.rb
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - config/**/*.rb
    - bin/*
    - Gemfile

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*.rb

Naming/FileName:
  Exclude:
    - Guardfile

Style/ClassAndModuleChildren:
  Enabled: false
